export const COUNTRIES = [
  { code: 'KR', name: '대한민국', nameEn: 'South Korea' },
  { code: 'US', name: '미국', nameEn: 'United States' },
  { code: 'JP', name: '일본', nameEn: 'Japan' },
  { code: 'CN', name: '중국', nameEn: 'China' },
  { code: 'GB', name: '영국', nameEn: 'United Kingdom' },
  { code: 'FR', name: '프랑스', nameEn: 'France' },
  { code: 'DE', name: '독일', nameEn: 'Germany' },
  { code: 'IT', name: '이탈리아', nameEn: 'Italy' },
  { code: 'ES', name: '스페인', nameEn: 'Spain' },
  { code: 'CA', name: '캐나다', nameEn: 'Canada' },
  { code: 'AU', name: '호주', nameEn: 'Australia' },
  { code: 'TH', name: '태국', nameEn: 'Thailand' },
  { code: 'VN', name: '베트남', nameEn: 'Vietnam' },
  { code: 'IN', name: '인도', nameEn: 'India' },
  { code: 'MX', name: '멕시코', nameEn: 'Mexico' },
  { code: 'BR', name: '브라질', nameEn: 'Brazil' },
  { code: 'OTHER', name: '기타', nameEn: 'Other' },
] as const;
