-- 재료 보관기간(shelf_life_days) 데이터 시드 + prod 누락 흔한 재료 14종 보강.
-- 출처: USDA FoodKeeper (미 공공도메인, Pantry/Refrigerate/Freeze Max·DOP coalesce → 일수).
-- 한국 미세조정: 대파 냉장 14. 우유 냉장 7(FoodKeeper는 포장표시일이라 표준 개봉후값).
-- 멱등: INSERT 는 NOT EXISTS 가드, UPDATE 는 name 기준. dev/prod 모두 안전 재적용.
-- 컬럼 생성은 20260603_ingredient_shelf_life.sql 선행.

-- (1) prod master 에 없던 흔한 base 재료 보강 (dev→공통). V2 base 링크는 standalone(null).
INSERT INTO ingredients_master (name, name_ko, category, emoji, is_processed, aliases, shelf_life_days, status)
SELECT v.name, v.name_ko, v.category, v.emoji, v.is_processed, v.aliases, v.sl, 'approved'
FROM (VALUES
  ('버터','버터','dairy','🧈',false, ARRAY['butter']::text[], '{"냉동":270,"냉장":60}'::jsonb),
  ('치즈','치즈','dairy','🧀',true, ARRAY['cheese']::text[], '{"냉동":180,"냉장":180}'::jsonb),
  ('모짜렐라','모짜렐라','dairy','🧀',true, ARRAY['모짜렐라치즈','모차렐라','mozzarella']::text[], '{"냉동":120,"냉장":30}'::jsonb),
  ('닭가슴살','닭가슴살','meat','🍗',false, ARRAY['chicken breast']::text[], '{"냉동":270,"냉장":2}'::jsonb),
  ('목살','목살','meat','🥩',false, NULL::text[], '{"냉동":360,"냉장":5}'::jsonb),
  ('삼겹살','삼겹살','meat','🥩',false, NULL::text[], '{"냉동":360,"냉장":5}'::jsonb),
  ('항정살','항정살','meat','🥩',false, ARRAY['pork jowl']::text[], '{"냉동":360,"냉장":5}'::jsonb),
  ('느타리버섯','느타리버섯','mushroom','🍄',false, ARRAY['느타리','oyster mushroom']::text[], '{"냉동":360,"냉장":7}'::jsonb),
  ('새송이버섯','새송이버섯','mushroom','🍄',false, ARRAY['새송이','king oyster mushroom','king trumpet mushroom']::text[], '{"냉동":360,"냉장":7}'::jsonb),
  ('양송이버섯','양송이버섯','mushroom','🍄',false, ARRAY['양송이','button mushroom','white mushroom']::text[], '{"냉동":360,"냉장":7}'::jsonb),
  ('표고버섯','표고버섯','mushroom','🍄',false, ARRAY['표고','shiitake','shiitake mushroom']::text[], '{"냉동":360,"냉장":7}'::jsonb),
  ('베이컨','베이컨','processed','🥓',true, ARRAY['bacon']::text[], '{"냉동":30,"냉장":7}'::jsonb),
  ('소시지','소시지','processed','🌭',true, ARRAY['sausage','비엔나','비엔나소시지']::text[], '{"냉동":60,"냉장":7}'::jsonb),
  ('햄','햄','processed','🍖',true, ARRAY['ham']::text[], '{"냉동":60,"냉장":14}'::jsonb)
) AS v(name, name_ko, category, emoji, is_processed, aliases, sl)
WHERE NOT EXISTS (SELECT 1 FROM ingredients_master m WHERE m.name = v.name);

-- (2) 보관기간 값 (name 기준, 멱등).
UPDATE ingredients_master m SET shelf_life_days = v.sl FROM (VALUES
  ('가지', '{"냉동": 240, "냉장": 7, "상온": 1}'::jsonb),
  ('감자', '{"냉동": 360, "냉장": 14, "상온": 60}'::jsonb),
  ('고구마', '{"상온": 21}'::jsonb),
  ('고등어', '{"냉동": 90, "냉장": 2}'::jsonb),
  ('고추', '{"냉동": 240, "냉장": 14}'::jsonb),
  ('느타리버섯', '{"냉동": 360, "냉장": 7}'::jsonb),
  ('단호박', '{"냉동": 360, "냉장": 90, "상온": 42}'::jsonb),
  ('달걀', '{"냉장": 35}'::jsonb),
  ('닭가슴살', '{"냉동": 270, "냉장": 2}'::jsonb),
  ('닭고기', '{"냉동": 360, "냉장": 2}'::jsonb),
  ('당근', '{"냉동": 360, "냉장": 21}'::jsonb),
  ('대파', '{"냉동": 360, "냉장": 14, "상온": 30}'::jsonb),
  ('동태', '{"냉동": 240, "냉장": 2}'::jsonb),
  ('돼지고기', '{"냉동": 360, "냉장": 5}'::jsonb),
  ('두부', '{"냉동": 150, "냉장": 7}'::jsonb),
  ('라임', '{"냉장": 21, "상온": 10}'::jsonb),
  ('레몬', '{"냉장": 21, "상온": 10}'::jsonb),
  ('마늘', '{"냉동": 30, "냉장": 14, "상온": 30}'::jsonb),
  ('모짜렐라', '{"냉동": 120, "냉장": 30}'::jsonb),
  ('목살', '{"냉동": 360, "냉장": 5}'::jsonb),
  ('무', '{"냉장": 14}'::jsonb),
  ('미니파프리카', '{"냉동": 240, "냉장": 14}'::jsonb),
  ('바나나', '{"냉동": 90, "냉장": 3}'::jsonb),
  ('방울토마토', '{"냉동": 60}'::jsonb),
  ('배추', '{"냉동": 360, "냉장": 14}'::jsonb),
  ('버섯', '{"냉동": 360, "냉장": 7}'::jsonb),
  ('버터', '{"냉동": 270, "냉장": 60}'::jsonb),
  ('베이컨', '{"냉동": 30, "냉장": 7}'::jsonb),
  ('브로콜리', '{"냉동": 360, "냉장": 5}'::jsonb),
  ('비트', '{"냉동": 240, "냉장": 14, "상온": 1}'::jsonb),
  ('사과', '{"냉동": 240, "냉장": 42, "상온": 21}'::jsonb),
  ('삼겹살', '{"냉동": 360, "냉장": 5}'::jsonb),
  ('상추', '{"냉장": 7}'::jsonb),
  ('새송이버섯', '{"냉동": 360, "냉장": 7}'::jsonb),
  ('새우', '{"냉동": 540, "냉장": 3}'::jsonb),
  ('생강', '{"냉동": 180, "냉장": 21, "상온": 5}'::jsonb),
  ('셀러리', '{"냉동": 360, "냉장": 14}'::jsonb),
  ('소고기', '{"냉동": 360, "냉장": 5}'::jsonb),
  ('소시지', '{"냉동": 60, "냉장": 7}'::jsonb),
  ('숙주', '{"냉장": 10}'::jsonb),
  ('시금치', '{"냉장": 7}'::jsonb),
  ('식빵', '{"냉동": 150, "상온": 18}'::jsonb),
  ('쌀', '{"상온": 730}'::jsonb),
  ('아스파라거스', '{"냉동": 150, "냉장": 4}'::jsonb),
  ('애호박', '{"냉동": 360, "냉장": 5, "상온": 5}'::jsonb),
  ('양배추', '{"냉동": 360, "냉장": 14}'::jsonb),
  ('양상추', '{"냉장": 14}'::jsonb),
  ('양송이버섯', '{"냉동": 360, "냉장": 7}'::jsonb),
  ('양파', '{"냉동": 360, "냉장": 60, "상온": 30}'::jsonb),
  ('연어', '{"냉동": 90, "냉장": 2}'::jsonb),
  ('오렌지', '{"냉장": 21, "상온": 10}'::jsonb),
  ('오이', '{"냉장": 6}'::jsonb),
  ('우유', '{"냉동": 90, "냉장": 7}'::jsonb),
  ('쪽파', '{"냉동": 360, "냉장": 7, "상온": 30}'::jsonb),
  ('청고추', '{"냉동": 240, "냉장": 14}'::jsonb),
  ('청양고추', '{"냉동": 240, "냉장": 14}'::jsonb),
  ('청피망', '{"냉동": 240, "냉장": 14}'::jsonb),
  ('치즈', '{"냉동": 180, "냉장": 180}'::jsonb),
  ('콩나물', '{"냉장": 10}'::jsonb),
  ('토마토', '{"냉동": 60}'::jsonb),
  ('파인애플', '{"냉동": 360, "냉장": 7}'::jsonb),
  ('파프리카', '{"냉동": 240, "냉장": 14}'::jsonb),
  ('표고버섯', '{"냉동": 360, "냉장": 7}'::jsonb),
  ('풋고추', '{"냉동": 240, "냉장": 14}'::jsonb),
  ('피망', '{"냉동": 240, "냉장": 14}'::jsonb),
  ('항정살', '{"냉동": 360, "냉장": 5}'::jsonb),
  ('햄', '{"냉동": 60, "냉장": 14}'::jsonb),
  ('홍고추', '{"냉동": 240, "냉장": 14}'::jsonb),
  ('홍피망', '{"냉동": 240, "냉장": 14}'::jsonb)
) AS v(name, sl) WHERE m.name = v.name;
